on:
  push:
    branches:
      - master
jobs:
  action:
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Build image
        run: docker build -t nebula/docs:master .
      - name: Deploy image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: docker stop nebula-docs || true
